### ISSUE TITLE
Add prompt 'are you sure you want to leave this page without saving your changes?' on moving forward to next 

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/vue-pybossa-frontend#124]
See https://github.com/LibCrowds/libcrowds-viewer/issues/134

**Comment by alexandermendes** [comment]
We can add in a little warning message now, although this might get annoying if it has to be shown every time!

**Comment by mialondon** [comment]
Removing the option to browse forward should help this!

**Comment by mialondon** [comment]
@alexandermendes this will be redundant if we simplify the model and don't let people move forward.

**Comment by alexandermendes** [comment]
Yep cool, not sure where the issue for that has gone now but will tackle it here https://github.com/LibCrowds/vue-pybossa-frontend/issues/255

I guess that means we can close this one for now!
