### ISSUE TITLE
'Contribute' page should have option to list all active projects

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/vue-pybossa-frontend#140]
Without having to choose category by category... ideally this would be the default option to increase the likelihood of any one project capturing people's attention.

**Comment by alexandermendes** [comment]
Well we have something pretty close with the "Featured" projects section, which is the default and where the projects can be switched via the (upcoming) admin interface at any point.

**Comment by alexandermendes** [comment]
@mialondon Note that apart from the fact we created a whole new architecture to accommodate the seperation of projects by volume, there are advantages to retrieving projects by category. Namely the API returns them with pagination and additional stats attached (see http://docs.pybossa.com/en/latest/api.html#project-category-featured). There is no 'all' category. We could potentially get around this by making every project a featured project, although this will mean we lose the ability to highlight certain projects (maybe those we really want to finish off etc). Going to put this one on hold for now anyway as there are lots of other more noticable issues

**Comment by alexandermendes** [comment]
The `/categories/<short_name>` endpoint adds various additional fields to the projects such as `n_volunteers` and `overall_progress` (See http://docs.pybossa.com/en/latest/api.html#admin-featured-projects). There is no "All" category.

While we can retrieve all projects via a different route they won't have these stats attached. So I would suggest we tackle this by renaming "Featured" to "All", or "Active", or whatever other word we want to use. As each project is created it would just be an extra few mouse clicks to add it to this list.

**Comment by alexandermendes** [comment]
Relies on https://github.com/LibCrowds/vue-pybossa-frontend/issues/254

**Comment by alexandermendes** [comment]
Covered by #254
