### ISSUE TITLE
Help box in item view: No scroll

### ISSUE THREAD

**Issue by RachaelKotarski** [LibCrowds/vue-pybossa-frontend#145]
If you open the Help box when viewing an item for annotation, the help box does not have a scroll bar - so it's not possible to view the whole content of the box.

Occurs in IE11 in Windows 7, but is OK in Chrome on the same machine.
![libcrowds](https://user-images.githubusercontent.com/1162788/29458164-acc3d3a2-8415-11e7-9e92-0c20da61bb1b.png)

**Comment by alexandermendes** [comment]
Thanks, I'll address this with the next update to the viewer module

**Comment by alexandermendes** [comment]
Covered by latest LibCrowds Viewer version (https://github.com/LibCrowds/libcrowds-viewer), will be fixed with the next update to the master branch.
