### ISSUE TITLE
Browser issues

### ISSUE THREAD

**Issue by corined** [LibCrowds/vue-pybossa-frontend#152]
In IE11  I have to move the scroll bar way to the right to be able to see the Contribute button. Not obvious, In Chrome, it displays immediately.

Once I have submitted a few items, it is not clear how you get out, apart from closing the browser window down. If you click the back browser button, you get back on the page where you could pick another project but the Contribute button now only displays if you hover over it (issue with both browsers)

**Comment by alexandermendes** [comment]
Thanks, a couple of these have been fixed in the current development version, I'll leave this open so that I make sure to check.

**Comment by alexandermendes** [comment]
The second issue has been fixed with project navigation being added to the projects. I still need to check the first.

**Comment by alexandermendes** [comment]
I think the first issue should now be fixed too (sorry that took a while)!
