### ISSUE TITLE
Post-usability testing fixes: add big {{ name }} heading to landing page

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/vue-pybossa-frontend#168]
The project branding needs to be boosted a bit. Ideally in future we'd have a project logo that incorporates playbills to go in that space, but this is a quick fix for now.

**Comment by alexandermendes** [comment]
A logo that represents a playbills sounds tricky! But I do like the idea of having a logo!

**Comment by alexandermendes** [comment]
Not totally convinced but I guess something like this

![image](https://user-images.githubusercontent.com/5636273/29941378-4b84881e-8e8a-11e7-9969-bfcfa4025f54.png)
