### ISSUE TITLE
Post-usability testing fixes: simplify category / project view controls

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/vue-pybossa-frontend#175]
For now, desaturate the blue used in the grid/list view icons so they stop distracting people from getting started.

**Comment by mialondon** [comment]
Usability test quote 'it's distracting me from just going for it'

**Comment by alexandermendes** [comment]
@mialondon So my idea for this would be something like this:

![image](https://user-images.githubusercontent.com/5636273/29940341-ce6965dc-8e86-11e7-9e75-025410f8f970.png)
