### ISSUE TITLE
Post-usability testing fixes: all text and images within project/set of tasks block link to task page

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/vue-pybossa-frontend#176]

**Comment by alexandermendes** [comment]
So the whole card basically becomes the link

**Comment by alexandermendes** [comment]
https://github.com/LibCrowds/vue-pybossa-frontend/commit/64048f0853d7dd75d33e931105d4fa584101c88d

**Comment by alexandermendes** [comment]
Note: The whole card isn't forming the link due to the upcoming individual project menu
