### ISSUE TITLE
Post-usability testing fixes: every project/set of tasks must have a representative image; hide project gravatar

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/vue-pybossa-frontend#177]

**Comment by alexandermendes** [comment]
Thumbnail gravatars replaced with more generic and less offensive placeholder :wink:

![image](https://user-images.githubusercontent.com/5636273/29982516-ed9f194c-8f49-11e7-9d5d-f460b778cd0e.png)

The uploading of custom project thumbnails isn't a code issue, it can be done at any point via the admin interface, so closing.
