### ISSUE TITLE
Post-usability testing fixes: update 'mark' task description

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/vue-pybossa-frontend#178]
Along the lines of 'Draw a rectangle with your mouse or trackpad around the title, then press the green tick to complete it. When you've marked all the titles on a page, press save.'

Update after testing on iPad!

**Comment by mialondon** [comment]
Mention that it's part of a sequence of tasks; transcribe is a separate task.

**Comment by alexandermendes** [comment]
I guess we can also close this (see https://github.com/LibCrowds/project-playbills/issues/11)
