### ISSUE TITLE
Task-specific help blocks

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/vue-pybossa-frontend#182]
A post-usability testing fix - it'd be great to have task-specific extended help as well as general 'how controls work' sections on the help pages for specific types of task e.g. mark, transcribe, verify.

**Comment by mialondon** [comment]
All task descriptions should include: a definition of the task e.g. type in names of plays - what, why, and task size e.g. marking is very quick, typing titles takes longer, typing personal names could take ages.

**Comment by mialondon** [comment]
@alexandermendes can we get this one into the next release? OTOH, if the help text is imported when the task is set up, and can't easily be changed, we'll want to take longer with it, using this week to write the text and test it on staging next week.

**Comment by alexandermendes** [comment]
Ah yes, so let's add this to our next milestone too. 

In fact, it will be possible to update the help text after the tasks are created if we really need to. Although it becomes more of a hassle the more projects we have up there (as you have to run through the update process for each one) so we probably want to avoid if possible.

So much documentation to write! Will try to do it as I go along now.

**Comment by alexandermendes** [comment]
So to confirm, I'll tackle the actual functionality of how the text is added to the site, then we can review and fill in the content, if that sounds ok?

**Comment by mialondon** [comment]
Ok

**Comment by alexandermendes** [comment]
So I'll close this one as being more about putting the functionality in place - we also have https://github.com/LibCrowds/project-playbills/issues/11 open to deal with the actual content

**Comment by mialondon** [comment]
@alexandermendes are the images displaying for you? e.g. I can't see it on the help modal on https://dev.libcrowds.com/collection/playbills/project/transcribe_titles_theatre_royal_margate_1796-1797/presenter/

**Comment by alexandermendes** [comment]
Hmm strange, yeah I can see them, and they're just coming straight from GitHub so I doubt they would be being blocked for any reason...

In fact, for the project above the image is loading exactly the same way as it is below

![Example](https://cdn.rawgit.com/LibCrowds/project-playbills/b15721d6/assets/transcribe_titles.gif)

**Comment by mialondon** [comment]
![date_api_bl_uk_image_iiif_ark__81055_vdc_100022589091_0x0000b6_full_1000 16](https://user-images.githubusercontent.com/380763/31012325-4f307bd6-a509-11e7-9aa2-939cbb561819.png)

Top of playbill showing date, title, theatre name, genre, etc.

**Comment by mialondon** [comment]
![genres_ theatre royal margate 1796-1797 www_libcrowds_com_collection_pla](https://user-images.githubusercontent.com/380763/31013005-f3ef38b8-a50b-11e7-8dbe-8d1808b56b04.png)

Showing highlighted title for genre help text
