### ISSUE TITLE
Post-usability testing fix: remove 'edit' button from rhs marked regions area

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/vue-pybossa-frontend#184]

**Comment by alexandermendes** [comment]
This issue was moved to LibCrowds/libcrowds-viewer#215

**Comment by alexandermendes** [comment]
Reopening this to track here (although will implement the actual change in the viewer repo). 

I'm not entirely sure we want to remove the edit option, and in fact remember implementing it specifically when asked "how do I edit selections?"

However, I will basically set this as a config variable so it can be switched on and off.

**Comment by mialondon** [comment]
@alexandermendes is this small enough to fit into the next release?

**Comment by alexandermendes** [comment]
@mialondon We have quite a lot there already, so perhaps I'll tackle a few first and see in a couple of days...but probably!

**Comment by alexandermendes** [comment]
Also see https://github.com/LibCrowds/vue-pybossa-frontend/issues/290
