### ISSUE TITLE
Post-usability testing fixes: work out how 'share' button should behave

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/vue-pybossa-frontend#189]
Like the IIIF viewer (screenshot below) or more like a social media share button? 
![uvshareexample](https://user-images.githubusercontent.com/380763/29934743-358e4d8a-8e74-11e7-8a7d-3c8a3a436913.png)

**Comment by alexandermendes** [comment]
So I would suggest a combination of both - open up a menu as above that contains social media buttons along with a 'Copy to Clipboard' button.

**Comment by alexandermendes** [comment]
This issue was moved to LibCrowds/libcrowds-viewer#217
