### ISSUE TITLE
Add category descriptions

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/vue-pybossa-frontend#20]
Where do we want to put the category descriptions? A separate page for each volume? Some kind of a more details button? Something else?

**Comment by alexandermendes** [comment]
Open to suggestions, of course, but I reckon something like a page with more details for each category but to not require users to move through it to get to the projects. Then on the main 'Projects' page we can link to this with 'More details about category x'.

**Comment by mialondon** [comment]
How's 'category' defined in this context?

I'm wondering if we should skip the word Projects and just use Volumes on e.g. https://playbills.libcrowds.com/projects where it says 'Each Playbills project is a collection of similar tasks on a single volume.' Internally we'd know that volume = project, but externally it's one less piece of jargon for someone to learn.

**Comment by alexandermendes** [comment]
Yeah, I agree that the terminology isn't all that clear, it is described a bit on the projects page. So the hierarchy for the database model is:

> Category > Project > Task > Task Run

Taking the playbills site as an example this translates as :

> Volume > Project (a collection of tasks) > Task (a task for each image) > Task Run (three for each task)

So actually volume = category! Then we have multiple projects for each volume. So, perhaps it would make sense to rename Category to Volume throughout the site.

**Comment by mialondon** [comment]
@alexandermendes ah, ok! That makes sense.

**Comment by mialondon** [comment]
Text to write per volume, from discussion: 'very brief catch-lines – an interesting name, noteworthy play. Just a sentence or two – a name [e.g. a prolific actor, notable figure etc] to look out for as they go through the sheets.'

Brief instructions will also be needed for each task (to appear on the task page). Other text is probably needed but it's hard to list until we've seen the interfaces.

**Comment by alexandermendes** [comment]
Covered in https://github.com/LibCrowds/vue-pybossa-frontend/issues/27
