### ISSUE TITLE
Are stats updating properly?

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/vue-pybossa-frontend#206]
I just did this whole volume anonymously but it's showing no anonymous contributions

https://backend.libcrowds.com/project/identify_titles_theatre_royal_margate_1796-1797/stats

**Comment by alexandermendes** [comment]
Well again they will be cached for some amount of time. but let's not worry about the PyBossa default theme as we won't be using it!

**Comment by alexandermendes** [comment]
Closing this one and will deal with it when we implement the per-project stats in https://github.com/LibCrowds/vue-pybossa-frontend/issues/241
