### ISSUE TITLE
/account/{{ name }}/update should lead to the profile settings page

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/vue-pybossa-frontend#209]
Partly because the oauth redirects can be sent back here, so after signing up for the first time the user gets a message to update their email but is sent to the API settings page, which makes no sense! They should be set to their profile settings page instead.

**Comment by mialondon** [comment]
@alexandermendes not sure how to test this one?

**Comment by alexandermendes** [comment]
So basically visiting `https://{our-dev-server}/account/mia/update` should redirect you to a profile settings page with a form to update your email address, username, etc.

**Comment by mialondon** [comment]
@alexandermendes thanks! Should the avatar function work? The 'browse' button didn't open a dialogue (Firefox, work PC).

Also, the avatar window seems to be overlaying the profile editing screen in the screenshot below.
![dev_libcrowds_com_account_mia_update_avatar](https://user-images.githubusercontent.com/380763/30386467-cff546d0-98a1-11e7-8207-ee51fde33f34.png)

**Comment by alexandermendes** [comment]
Yeah we do have a problem there - I'll deal with it here https://github.com/LibCrowds/vue-pybossa-frontend/issues/101

Although I probably won't manage to get to it this week. Out of the 400 or so users registered so far probably less than 10 actually used this, so maybe no one will notice if we leave it for a week or two!

**Comment by mialondon** [comment]
@alexandermendes agreed!
