### ISSUE TITLE
Implement newsletter signup process

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/vue-pybossa-frontend#21]
Screen text and URL below. It might also throw an error if you don't try to sign up for the newsletter, I'm not sure. 

https://www.libcrowds.com/account/newsletter?subscribe=True&next=%2F
Ooops, Something's broken

It looks as though there's a problem with our system.

We will try to fix it as soon as we can.

**Comment by mialondon** [comment]
Ah, it's because I was already subscribed to the MailChimp list. At some point it'd be great to catch the ListAlreadySubscribedError exception and handle it gracefully.

**Comment by alexandermendes** [comment]
Ah thanks, I think it basically doesn't expect that you will have already subscribed by other means there's also a flag in the database to show if a user is subscribed and if so that page isn't shown. Probably means submitting a PR to PyBossa, I'll do this at some point.

**Comment by alexandermendes** [comment]
So we'll be handling this differently in the new theme but will leave this here as a reminder
