### ISSUE TITLE
Sign-up page doesn't acknowledge success after hitting 'sign up' button

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/vue-pybossa-frontend#215]
So I kept hitting it and ended up with five registration emails :)

**Comment by alexandermendes** [comment]
Right, so this is due to the email confirmation being switched on (which it isn't in my local dev server and is why I didn't notice it)!

We need to handle the reponse:

```
{
  "status": "sent",
  "template": "account/account_validation.html",
  "title": "Account validation"
}
```
