### ISSUE TITLE
In responsive mode, put the 'sorting options' block below the 'projects'

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/vue-pybossa-frontend#229]

**Comment by alexandermendes** [comment]
Or just hide it on smaller screens (actually a bit easier) and just leave it as a larger screen option.

**Comment by mialondon** [comment]
@alexandermendes works for me!

**Comment by alexandermendes** [comment]
@mialondon hmm, actually just noticed an issue with this solution - it means that a user can no longer look back at completed projects on a small screen. But perhaps this doesn't matter, it's probably a very rarely used option anyway.

**Comment by mialondon** [comment]
@alexandermendes we should probably have a general message saying that the device version isn't as functional as the full version. What's the breakpoint set at, btw? On my screen it goes into responsive at what looks like 800px or so.

**Comment by alexandermendes** [comment]
So we have a few different ones but for this page the layout changes at 1200px. Below that it's too difficult to fit everything onto the screen.

Not sure about the message saying you're using functionality on a smaller screen - if people are on a smaller screen there isn't really a lot they can do with that message! Perhaps a candidate for the FAQ section?

**Comment by mialondon** [comment]
@alexandermendes I think there's a pattern where people see a tweet, check out a project, and save it to check out properly later if they think it's worth it. Most people aren't stuck solely on a device (though given the digital divide we know that a certain percentage is).
