### ISSUE TITLE
Missing Thumbnails On Convert-a-Card Projects

### ISSUE THREAD

**Issue by ndalyrose** [LibCrowds/vue-pybossa-frontend#232]
Missing pics here for the Urdu and Chinese Projects. https://www.libcrowds.com/collection/convertacard/contribute/

**Comment by alexandermendes** [comment]
Thanks, and any suggestions for nice images would be very welcome! Because I know you're good at finding those (or I can't be bothered...yeah, the first one) :stuck_out_tongue_winking_eye:

**Comment by alexandermendes** [comment]
We also need one for the Indonesian projects - even though they're complete people might want to go back and have a look.

Of course we can also pass this soft of thing on to our curators to help give them another element of input/ownership.

**Comment by alexandermendes** [comment]
Will deal with this here https://github.com/LibCrowds/vue-pybossa-frontend/issues/295
