### ISSUE TITLE
Fix docs

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/vue-pybossa-frontend#248]
The configuration guide has been written but it's not building.

**Comment by alexandermendes** [comment]
Improving documentation will be an ongoing process but we can at least get started here.

**Comment by alexandermendes** [comment]
A bit tricky to check until it's merged into master, as the docs are built from the master branch but a few improvements have been made and the readme on the frontpage of this repo can now be seen linking to the new git book.

**Comment by mialondon** [comment]
@alexandermendes great! Just make the context clear e.g. how this relates to BL systems and what kind of user would read this documentation e.g. sysadmin, curator, etc.

**Comment by alexandermendes** [comment]
So I'll close this for now as the process is in place and open a separate one to deal with the comment above - see #291

In general improving the docs will be another ongoing process (and there is a bit of catching up to do)!
