### ISSUE TITLE
Add DOI

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/vue-pybossa-frontend#249]
See https://guides.github.com/activities/citable-code/

This has actually been activate already (it's pretty cool http://doi.org/10.5281/zenodo.888397), just add the badge to the readme

**Comment by mialondon** [comment]
@alexandermendes another one I'm not sure how to review!

**Comment by alexandermendes** [comment]
Just check the link!

http://doi.org/10.5281/zenodo.888397

It's a small one but it means different versions of our code become citable using DOIs, which is pretty cool.

**Comment by alexandermendes** [comment]
Worth checking the GitHub guide linked above too for a general overview, this kind of thing could come in handy for any of us working with research software.
