### ISSUE TITLE
Update task block to say how many pages in a volume

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/vue-pybossa-frontend#256]
Feedback from Adam: the %age complete is good, but there's no way to know what that means without a sense of how many pages are in the volume. 

@alexandermendes can we add something like '_x_ pages in project' to the %age/number of volunteers section?

**Comment by alexandermendes** [comment]
Yeah sure, we did actually have it previously but took at out as the stats on the card were getting a bit squashed. I'll put it back!

**Comment by mialondon** [comment]
@alexandermendes fab, thanks!

**Comment by mialondon** [comment]
@alexandermendes looks good, and not too cluttered. If 'tasks' means pages then ideally it'd say that, as it's not a meaningful term for volunteers. Or '_x_ tasks on _y_ pages'.

**Comment by alexandermendes** [comment]
Ah, so this is another feature that I've added, but need to generate the docs. We can specify project-specific terminology for `category` (e.g. volumes), `project`, `task` and `task run`. This way the code still makes sense when linking up with PyBossa but we can have the freedom to call these things whatever we like. I still think task makes the most sense - as the action is to complete a task, with the page being the input to that task - but I'll leave this up to everyone else to decide!

**Comment by alexandermendes** [comment]
See https://github.com/LibCrowds/libcrowds-frontend-settings/blob/master/playbills/config.js

and https://github.com/LibCrowds/vue-pybossa-frontend/blob/master/docs/configuration.md (doc updates to come but as it's mainly for us I'm focussing on the more important bits first).

**Comment by mialondon** [comment]
@alexandermendes I suspect most people think 'tasks' are things you do on a page, and that the page is the primary object, but we can go with it for now and ask people what they think 'task' means in that context in later usability tests.
