### ISSUE TITLE
Transcription task UX notes - first pass

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/vue-pybossa-frontend#257]
A first pass after viewing https://libcrowds.github.io/libcrowds-viewer/ - ideally we'd validate/clarify them with some quick usability tests on staging. Update: did a quick test with Adam, notes incorporated.

* More task instructions needed, including lessons from mark task feedback. Draft first, then add to the task page
* It's not obvious which title is marked first - instructions re green highlight will help, but is it enough?

* Test colours re current highlight and other marked regions

* The page currently says 'Are you sure you want to submit this task? There is no going back!' which does make me pause but doesn't actually give me information to inform my decision. Should be something like 'Have you transcribed all marked sections of this page? You can only save a page once.' Even better, could the page compare the number of marked areas and transcriptions and use that information in the prompt? Sometimes there might be legit reasons for not transcribing everything, and perhaps here we could encourage people to leave a note.
* What information does the user have about being able to save work in progress? e.g. if they get a phonecall halfway through a long page of names
* It's not obvious how you move onto the next title - I took a punt and press 'enter' on my keyboard but others mightn't guess that.
* Longer titles (e.g. The Devil to Pay; Or, The Wives Metamorphosed.) don't fit into the text box so you can't easily glance over and check your transcription at the end.

* Type head for fields based on recent names

* Easter egg/celebration screen when get to the end of a volume/task queue

* Update instructions re how much we care about case and punctuation - help file?

* Clearly signal that typing names is a slightly different task - not just 'type what you see' - ignore spaces, punctuation

* Lots of discussion re going back/forward, also ability to add notes - discuss and decide feasible solution for now/long term. If can go back and not edit, then make it clearly a 'view only' mode. Other option might be to let people edit until the volume is submitted.

**Comment by alexandermendes** [comment]
I think that having multiple titles marked up might be confusing things. It does seem to me like having one bit of text highlighted and asking users to transcribe only that would solve a few of those! (i.e. it's then obvious what your transcribing and the submit button saves and moves on, as with the previous marking tasks).

But this is one we'll have to look at a bit more closely.

**Comment by christianalgar** [comment]
- After ”Transcribe the title exactly as you see on the page.”, could it help to clarify with something like “including typos, use of capitals and punctuation marks – use ? for any ambiguities”

- The Transcribe Persons could take a long time – and vary greatly between one playbill and the next in the sequence – is there a way for a user to save and return to the task or must it be completed in one sitting?

- Can someone skip around the sheet, or must the names be transcribed in sequence? Some people like to use a ‘scatter-gun’ approach, others like to proceed in order.

**Comment by alexandermendes** [comment]
Re Christian's second point, I think this might be another reason to only highlight and present one area at a time. That way it should be obvious that the "Save" button is for that selection and not the entire page.

Also, removing this from the current milestone and will divide it into separate issues and add it back later. We seem to have 10 issues in one here (although maybe a few of them have the same solution)!

**Comment by mialondon** [comment]
Moved items to https://trello.com/c/K0fzOA5W/89-usability-notes-compiled

**Comment by alexandermendes** [comment]
Thanks :smile:
