### ISSUE TITLE
Update libcrowds-viewer button text

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/vue-pybossa-frontend#268]
Add a config option to libcrowds-viewer to change the button text for the note and submit buttons.

**Comment by mialondon** [comment]
@alexandermendes great! Can you document the location of the config setting?

**Comment by alexandermendes** [comment]
Ah, so this is a config setting in the viewer module (see https://libcrowds.gitbooks.io/libcrowds-viewer-docs/configuration.html#buttons ).

In this frontend repo we set that here https://github.com/LibCrowds/vue-pybossa-frontend/blob/dev/src/components/presenters/LibcrowdsViewer.vue

So it's a one line fix but if we do want to change it again in future it's probably best to just raise another issue (e.g. Change the note button next to 'Some Text').

It's an idea for later though to make things like this configurable from the admin interface #293
