### ISSUE TITLE
Change docs URL in preparation for more full docs

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/vue-pybossa-frontend#380]
See https://docs.libcrowds.com/

**Comment by alexandermendes** [comment]
Note: considering renaming this repo (and therefore the docs title) to "LibCrowds" or "LibCrowds frontend", but not many people will see it anyway

**Comment by mialondon** [comment]
That sounds sensible - that way it's about the goal/bigger project rather than the technology.

**Comment by alexandermendes** [comment]
Yeah, it might be a tiny bit of a strange mix as the development/build setup bits will still need to be there for anyone who might do work on this at a later date, but we can mostly tailor it towards the actual frontend functionality etc.
