### ISSUE TITLE
Add project difficulty/time column

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/vue-pybossa-frontend#69]
_From @alexandermendes on April 19, 2017 16:49_

To allow sorting of quick tasks for busy people vs longer tasks.

- Perhaps see if I can add a flag to the project data model for this or just use the info field.
- Alternatively, pull in stats for average contribution time and use this to create flags or sort.

_Copied from original issue: LibCrowds/libcrowds-bs4-pybossa-theme#12_

**Comment by alexandermendes** [comment]
Use  `/project/<short_name>/stats` if we need to implement this

**Comment by alexandermendes** [comment]
This will require changes to the PyBossa code, putting on hold for now.

**Comment by alexandermendes** [comment]
This will also be dealt with in https://github.com/LibCrowds/vue-pybossa-frontend/issues/241

**Comment by mialondon** [comment]
@alexandermendes we should also mention task speed in the text

**Comment by alexandermendes** [comment]
Sure, we can do, 49.5 seconds so far!

https://backend.libcrowds.com/project/identify_titles_theatre_royal_margate_1796-1797/stats

**Comment by mialondon** [comment]
I meant more as a description e.g. this is a super-fast task, that takes x minutes.

**Comment by alexandermendes** [comment]
Sure, so we can still write whatever we like in the description but this is quite a handy feature for getting the actual times, which of course are always changing (maybe a marking task for one more complex volumes takes twice as long etc.). Should be visible on the staging server later today - just figuring out some final errors before releasing the next version.
